name: Rollout Waves

on:
  # run automatically
  push:
    branches: [ "main" ]
  # pull_request:
  #   branches: [ "main" ]

  # run manually
  workflow_dispatch:

jobs:
  wave-devtest:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: hello
        run: echo hello world

  wave-staging:
    needs: wave-devtest
    runs-on: ubuntu-latest
    environment: qa
    steps:
      - name: hello
        run: echo hello world

  wave-prod1:
    needs: wave-staging
    runs-on: ubuntu-latest
    environment: prod1
    steps:
      - name: hello
        run: echo hello world
      - name: failing
        run: |
          echo forcing an error
          exit 1

  wave-prod2:
    needs: wave-prod1
    runs-on: ubuntu-latest
    environment: prod2
    steps:
      - name: hello
        run: echo hello world

  wave-prod3:
    needs: wave-prod1
    runs-on: ubuntu-latest
    environment: prod3
    steps:
      - name: hello
        run: echo hello world

  wave-prod4:
    needs: wave-prod1
    runs-on: ubuntu-latest
    environment: prod4
    steps:
      - name: hello
        run: echo hello world

  wave-prod5:
    needs: wave-prod1
    runs-on: ubuntu-latest
    environment: prod5
    steps:
      - name: hello
        run: echo hello world

  wave-complete:
    needs: [wave-prod1, wave-prod2, wave-prod3, wave-prod4, wave-prod5]
    runs-on: ubuntu-latest
    steps:
      - name: hello
        run: echo commit!

  wave-catch:
    needs: wave-complete
    runs-on: ubuntu-latest
    if: ${{ failure() }}
    steps:
      - name: catch
        run: echo reverting changes!!
