name: Rollout Waves

on:
  # run automatically
  push:
    branches: [ "main" ]
  # pull_request:
  #   branches: [ "main" ]

  # run manually
  workflow_dispatch:
    inputs:
      cause_failure:
        description: 'Cause Failure'
        required: true
        default: 'false'

jobs:
  wave-devtest:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: hello
        run: echo "### configuring ${GITHUB_ACTION}"" >> $GITHUB_STEP_SUMMARY

  wave-staging:
    needs: wave-devtest
    runs-on: ubuntu-latest
    environment: qa
    steps:
      - name: hello
        run: echo "### configuring ${GITHUB_ACTION}"" >> $GITHUB_STEP_SUMMARY

  wave-prod1:
    needs: wave-staging
    runs-on: ubuntu-latest
    environment: prod1
    steps:
      - name: hello
        run: echo "### configuring ${GITHUB_ACTION}"" >> $GITHUB_STEP_SUMMARY
      - if: github.event.inputs.cause_failure == 'true'
        name: failing
        run: |
          echo forcing an error
          exit 1

  wave-prod2:
    needs: wave-prod1
    runs-on: ubuntu-latest
    environment: prod2
    steps:
      - name: hello
        run: echo "### configuring ${GITHUB_ACTION}"" >> $GITHUB_STEP_SUMMARY

  wave-prod3:
    needs: wave-prod1
    runs-on: ubuntu-latest
    environment: prod3
    steps:
      - name: hello
        run: echo "### configuring ${GITHUB_ACTION}"" >> $GITHUB_STEP_SUMMARY

  wave-prod4:
    needs: wave-prod1
    runs-on: ubuntu-latest
    environment: prod4
    steps:
      - name: hello
        run: echo "### configuring ${GITHUB_ACTION}"" >> $GITHUB_STEP_SUMMARY

  wave-prod5:
    needs: wave-prod1
    runs-on: ubuntu-latest
    environment: prod5
    steps:
      - name: hello
        run: echo "### configuring ${GITHUB_ACTION}"" >> $GITHUB_STEP_SUMMARY

  wave-complete:
    needs: [wave-prod1, wave-prod2, wave-prod3, wave-prod4, wave-prod5]
    runs-on: ubuntu-latest
    steps:
      - name: hello
        run: echo "## committing changes!" >> $GITHUB_STEP_SUMMARY

  wave-if-failure:
    needs: wave-complete
    runs-on: ubuntu-latest
    if: ${{ failure() }}
    steps:
      - name: catch
        run: echo "## reverting changes!"  >> $GITHUB_STEP_SUMMARY
